Hw hibernate kostevich
gigbat/hibernate-cinema pull request #1
Opened 2021-01-26 11:21 UTC by gigbat

2021-01-26 15:14 UTC, ivlytvynets requested changes

2021-01-26 15:14 UTC, ivlytvynets commented on pom.xml
> +    </dependencies>
chechstyle plugin

2021-01-26 15:14 UTC, ivlytvynets commented on src/main/java/com/dev/cinema/dao/impl/MovieDaoImpl.java
> +            throw new RuntimeException("Can't insert movie entity", e);
throw custom exception

2021-01-26 15:14 UTC, ivlytvynets commented on src/main/java/com/dev/cinema/util/HibernateUtil.java
> +            throw new RuntimeException("Error creating Session Factory", e);
I would throw custom exception here, too. But now it's up to you

2021-01-26 15:23 UTC, ivlytvynets approved these changes

2021-01-27 08:18 UTC, Sofasmile requested changes

2021-01-27 08:18 UTC, Sofasmile commented on src/main/java/com/dev/cinema/dao/impl/MovieDaoImpl.java
> +            movie.setId(id);
https://mate-academy.github.io/jv-program-fulltime/03_hibernate/checklist/hibernate_01.html

2021-01-27 08:18 UTC, Sofasmile commented on src/main/java/com/dev/cinema/dao/impl/MovieDaoImpl.java
> +            throw new DataProcessingException("Can't insert movie entity", e);
```suggestion
            throw new DataProcessingException("Can't insert movie entity " + movie, e);
```

2021-01-27 08:29 UTC, gigbat commented on src/main/java/com/dev/cinema/dao/impl/MovieDaoImpl.java
> +            movie.setId(id);
done

2021-01-27 10:59 UTC, RomanDubovskyi approved these changes

2021-01-27 11:01 UTC, merged