Hw spring kostevich
gigbat/hibernate-cinema pull request #6
Opened 2021-02-11 13:13 UTC by gigbat

2021-02-11 13:15 UTC, ivlytvynets approved these changes

2021-02-11 17:49 UTC, dmytro-hryhoruk requested changes

2021-02-11 17:49 UTC, dmytro-hryhoruk commented on src/main/java/com/dev/cinema/config/AppConfig.java
> +        "com.dev.cinema.service.impl"
```suggestion
        "com.dev.cinema.service"
```

2021-02-11 17:49 UTC, dmytro-hryhoruk commented on src/main/java/com/dev/cinema/config/AppConfig.java
> +        "com.dev.cinema.dao.impl",
```suggestion
        "com.dev.cinema.dao",
```

2021-02-11 17:49 UTC, dmytro-hryhoruk commented on src/main/java/com/dev/cinema/config/AppConfig.java
> +        "com.dev.cinema.service.impl"
security

2021-02-11 21:16 UTC, gigbat commented on src/main/java/com/dev/cinema/config/AppConfig.java
> +        "com.dev.cinema.service.impl"
done

2021-02-11 21:17 UTC, gigbat commented on src/main/java/com/dev/cinema/config/AppConfig.java
> +        "com.dev.cinema.dao.impl",
done

2021-02-12 08:21 UTC, dmytro-hryhoruk approved these changes

2021-02-12 10:16 UTC, merged